proj/views/item_area_views.py
from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect

from .. import db
from proj.models import Item_area
from proj.forms import QuestionForm, AnswerForm

bp = Blueprint('item_area', __name__, url_prefix='/item_area')

@bp.route('/list/')
def _list():
    item_area_list=Item_area.query.order_by()
    return render_template('item_area/item_area_list.html', item_area_list=item_area_list)


@bp.route('/detail/<int:item_area_id>/')
def detail(item_area_id):
    form = AnswerForm()
    item_area=Item_area.query.get_or_404(item_area_id)
    return render_template('item_area/item_area_detail.html', item_area=item_area, form=form)
'''
@bp.route('/create/', methods=('GET', 'POST'))
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now())
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)
'''

proj/templates/item_area/item_area_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 아이템 영역 -->
    <h2 class="border-bottom py-2">{{ item_area.id }}. {{ item_area.area }}</h2>

    <!-- 아이템 제목 -->

    {% for item_title in item_area.item_title_set %}
    <h5 class="border-bottom my-3 py-2">{{ item_title.id }}. {{ item_title.title }}</h5>
        {% for item_content in item_title.item_content_set %}
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ item_content.content }}</div>
            </div>
        </div>
            {% if (item_content.usage == 3) %}
            <div class="mb-3">
                <textarea name="content" id="content" class="form-control" rows="3"></textarea>
            </div>
            {% else %}
                {% for item_example in item_content.item_example_set %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" name={{ item_content.id }} value={{ item_example.example }} id= {{ item_example.id }}>
                    <label class="form-check-label" for={{ item_example.id }}>
                    {{ item_example.example }}
                    </label>
                </div>
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endfor %}
</div>
{% endblock %}

proj/templates/item_area/item_area_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>아이템 영역</th>
        </tr>
        </thead>
        <tbody>
        {% if item_area_list %}
        {% for item_area in item_area_list %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>
                <a href="{{ url_for('item_area.detail', item_area_id=item_area.id) }}">{{ item_area.area }}</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">아이템이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}